services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:8080"
    volumes:
      - ./back/src:/app/src
      - ./back/nodemon.json:/app/nodemon.json
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - database
    networks:
      - mynetwork
  frontend:
    build: ./front
    ports:
      - "3001:3000"
    volumes:
      - ./front/src:/app/src
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - mynetwork
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database-configuration.sql:/docker-entrypoint-initdb.d/database-configuration.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
